package bloodbank.json_entites;
// Generated May 13, 2022 3:58:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BloodTransactions generated by hbm2java
 */
public class BloodTransactions  implements java.io.Serializable {


     private Integer transactionId;
     private BloodStock bloodStock;
     private Donors donors;
     private Patients patients;
     private Staff staff;
     private Date transactionDate;

    public BloodTransactions() {
    }

	
    public BloodTransactions(BloodStock bloodStock, Staff staff, Date transactionDate) {
        this.bloodStock = bloodStock;
        this.staff = staff;
        this.transactionDate = transactionDate;
    }
    public BloodTransactions(BloodStock bloodStock, Donors donors, Patients patients, Staff staff, Date transactionDate) {
       this.bloodStock = bloodStock;
       this.donors = donors;
       this.patients = patients;
       this.staff = staff;
       this.transactionDate = transactionDate;
    }
   
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }
    public BloodStock getBloodStock() {
        return this.bloodStock;
    }
    
    public void setBloodStock(BloodStock bloodStock) {
        this.bloodStock = bloodStock;
    }
    public Donors getDonors() {
        return this.donors;
    }
    
    public void setDonors(Donors donors) {
        this.donors = donors;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }




}


