package bloodbank.json_entites;
// Generated May 13, 2022 3:58:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BloodStock generated by hbm2java
 */
public class BloodStock  implements java.io.Serializable {


     private Integer bagId;
     private Staff staff;
     private String bloodType;
     private Date donationDate;
     private Set bloodTransactionses = new HashSet(0);

    public BloodStock() {
    }

	
    public BloodStock(Staff staff, String bloodType, Date donationDate) {
        this.staff = staff;
        this.bloodType = bloodType;
        this.donationDate = donationDate;
    }
    public BloodStock(Staff staff, String bloodType, Date donationDate, Set bloodTransactionses) {
       this.staff = staff;
       this.bloodType = bloodType;
       this.donationDate = donationDate;
       this.bloodTransactionses = bloodTransactionses;
    }
   
    public Integer getBagId() {
        return this.bagId;
    }
    
    public void setBagId(Integer bagId) {
        this.bagId = bagId;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }
    public Date getDonationDate() {
        return this.donationDate;
    }
    
    public void setDonationDate(Date donationDate) {
        this.donationDate = donationDate;
    }
    public Set getBloodTransactionses() {
        return this.bloodTransactionses;
    }
    
    public void setBloodTransactionses(Set bloodTransactionses) {
        this.bloodTransactionses = bloodTransactionses;
    }




}


