package bloodbank.json_entites;
// Generated May 13, 2022 3:58:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmpJobs generated by hbm2java
 */
public class EmpJobs  implements java.io.Serializable {


     private Integer jobId;
     private String job;
     private Set staffs = new HashSet(0);

    public EmpJobs() {
    }

	
    public EmpJobs(String job) {
        this.job = job;
    }
    public EmpJobs(String job, Set staffs) {
       this.job = job;
       this.staffs = staffs;
    }
   
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


