package bloodbank.json_entites;
// Generated May 13, 2022 3:58:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Patients generated by hbm2java
 */
public class Patients  implements java.io.Serializable {


     private Integer patientId;
     private Staff staff;
     private String firstName;
     private String lastName;
     private String gender;
     private String address;
     private String bloodType;
     private String natId;
     private Date dateOfBirth;
     private String primaryNumber;
     private String secondaryNumber;
     private Set patientHistories = new HashSet(0);
     private Set bloodTransactionses = new HashSet(0);

    public Patients() {
    }

	
    public Patients(Staff staff, String firstName, String lastName, String gender, String address, String bloodType, String natId, Date dateOfBirth, String primaryNumber) {
        this.staff = staff;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.address = address;
        this.bloodType = bloodType;
        this.natId = natId;
        this.dateOfBirth = dateOfBirth;
        this.primaryNumber = primaryNumber;
    }
    public Patients(Staff staff, String firstName, String lastName, String gender, String address, String bloodType, String natId, Date dateOfBirth, String primaryNumber, String secondaryNumber, Set patientHistories, Set bloodTransactionses) {
       this.staff = staff;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.address = address;
       this.bloodType = bloodType;
       this.natId = natId;
       this.dateOfBirth = dateOfBirth;
       this.primaryNumber = primaryNumber;
       this.secondaryNumber = secondaryNumber;
       this.patientHistories = patientHistories;
       this.bloodTransactionses = bloodTransactionses;
    }
   
    public Integer getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }
    public String getNatId() {
        return this.natId;
    }
    
    public void setNatId(String natId) {
        this.natId = natId;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getPrimaryNumber() {
        return this.primaryNumber;
    }
    
    public void setPrimaryNumber(String primaryNumber) {
        this.primaryNumber = primaryNumber;
    }
    public String getSecondaryNumber() {
        return this.secondaryNumber;
    }
    
    public void setSecondaryNumber(String secondaryNumber) {
        this.secondaryNumber = secondaryNumber;
    }
    public Set getPatientHistories() {
        return this.patientHistories;
    }
    
    public void setPatientHistories(Set patientHistories) {
        this.patientHistories = patientHistories;
    }
    public Set getBloodTransactionses() {
        return this.bloodTransactionses;
    }
    
    public void setBloodTransactionses(Set bloodTransactionses) {
        this.bloodTransactionses = bloodTransactionses;
    }




}


