package bloodbank.entites;
// Generated May 13, 2022 3:58:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BloodStock generated by hbm2java
 */
@Entity
@Table(name="blood_stock"
    ,catalog="blood_bank"
)
public class BloodStock  implements java.io.Serializable {


     private Integer bagId;
     private Staff staff;
     private String bloodType;
     private Date donationDate;
     private Set<BloodTransactions> bloodTransactionses = new HashSet<BloodTransactions>(0);

    public BloodStock() {
    }

	
    public BloodStock(Staff staff, String bloodType, Date donationDate) {
        this.staff = staff;
        this.bloodType = bloodType;
        this.donationDate = donationDate;
    }
    public BloodStock(Staff staff, String bloodType, Date donationDate, Set<BloodTransactions> bloodTransactionses) {
       this.staff = staff;
       this.bloodType = bloodType;
       this.donationDate = donationDate;
       this.bloodTransactionses = bloodTransactionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Bag_id", unique=true, nullable=false)
    public Integer getBagId() {
        return this.bagId;
    }
    
    public void setBagId(Integer bagId) {
        this.bagId = bagId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Doctor_id", nullable=false)
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    
    @Column(name="Blood_Type", nullable=false, length=10)
    public String getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Donation_Date", nullable=false, length=10)
    public Date getDonationDate() {
        return this.donationDate;
    }
    
    public void setDonationDate(Date donationDate) {
        this.donationDate = donationDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="bloodStock")
    public Set<BloodTransactions> getBloodTransactionses() {
        return this.bloodTransactionses;
    }
    
    public void setBloodTransactionses(Set<BloodTransactions> bloodTransactionses) {
        this.bloodTransactionses = bloodTransactionses;
    }




}


