package bloodbank.entites;
// Generated May 13, 2022 3:58:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BloodTransactions generated by hbm2java
 */
@Entity
@Table(name="blood_transactions"
    ,catalog="blood_bank"
)
public class BloodTransactions  implements java.io.Serializable {


     private Integer transactionId;
     private BloodStock bloodStock;
     private Donors donors;
     private Patients patients;
     private Staff staff;
     private Date transactionDate;

    public BloodTransactions() {
    }

	
    public BloodTransactions(BloodStock bloodStock, Staff staff, Date transactionDate) {
        this.bloodStock = bloodStock;
        this.staff = staff;
        this.transactionDate = transactionDate;
    }
    public BloodTransactions(BloodStock bloodStock, Donors donors, Patients patients, Staff staff, Date transactionDate) {
       this.bloodStock = bloodStock;
       this.donors = donors;
       this.patients = patients;
       this.staff = staff;
       this.transactionDate = transactionDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Transaction_id", unique=true, nullable=false)
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Bag_id", nullable=false)
    public BloodStock getBloodStock() {
        return this.bloodStock;
    }
    
    public void setBloodStock(BloodStock bloodStock) {
        this.bloodStock = bloodStock;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Donor_id")
    public Donors getDonors() {
        return this.donors;
    }
    
    public void setDonors(Donors donors) {
        this.donors = donors;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Patient_id")
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Doctor_id", nullable=false)
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="transaction_date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }




}


