package bloodbank.entites;
// Generated May 13, 2022 3:58:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diseases generated by hbm2java
 */
@Entity
@Table(name="diseases"
    ,catalog="blood_bank"
)
public class Diseases  implements java.io.Serializable {


     private Integer diseaseId;
     private String diseaseName;
     private Set<Donors> donorses = new HashSet<Donors>(0);
     private Set<PatientHistory> patientHistories = new HashSet<PatientHistory>(0);

    public Diseases() {
    }

	
    public Diseases(String diseaseName) {
        this.diseaseName = diseaseName;
    }
    public Diseases(String diseaseName, Set<Donors> donorses, Set<PatientHistory> patientHistories) {
       this.diseaseName = diseaseName;
       this.donorses = donorses;
       this.patientHistories = patientHistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Disease_id", unique=true, nullable=false)
    public Integer getDiseaseId() {
        return this.diseaseId;
    }
    
    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    
    @Column(name="Disease_Name", nullable=false)
    public String getDiseaseName() {
        return this.diseaseName;
    }
    
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }

@ManyToMany(fetch=FetchType.EAGER, mappedBy="diseaseses")
    public Set<Donors> getDonorses() {
        return this.donorses;
    }
    
    public void setDonorses(Set<Donors> donorses) {
        this.donorses = donorses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="diseases")
    public Set<PatientHistory> getPatientHistories() {
        return this.patientHistories;
    }
    
    public void setPatientHistories(Set<PatientHistory> patientHistories) {
        this.patientHistories = patientHistories;
    }




}


