package bloodbank.entites;
// Generated May 13, 2022 3:58:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmpJobs generated by hbm2java
 */
@Entity
@Table(name="emp_jobs"
    ,catalog="blood_bank"
    , uniqueConstraints = @UniqueConstraint(columnNames="Job") 
)
public class EmpJobs  implements java.io.Serializable {


     private Integer jobId;
     private String job;
     private Set<Staff> staffs = new HashSet<Staff>(0);

    public EmpJobs() {
    }

	
    public EmpJobs(String job) {
        this.job = job;
    }
    public EmpJobs(String job, Set<Staff> staffs) {
       this.job = job;
       this.staffs = staffs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Job_id", unique=true, nullable=false)
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    
    @Column(name="Job", unique=true, nullable=false, length=45)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="empJobs")
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }




}


