package bloodbank.entites;
// Generated May 13, 2022 3:58:53 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientHistory generated by hbm2java
 */
@Entity
@Table(name="patient_history"
    ,catalog="blood_bank"
)
public class PatientHistory  implements java.io.Serializable {


     private PatientHistoryId id;
     private Diseases diseases;
     private Patients patients;

    public PatientHistory() {
    }

    public PatientHistory(PatientHistoryId id, Diseases diseases, Patients patients) {
       this.id = id;
       this.diseases = diseases;
       this.patients = patients;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientId", column=@Column(name="Patient_id", nullable=false) ), 
        @AttributeOverride(name="diseaseId", column=@Column(name="Disease_id", nullable=false) ) } )
    public PatientHistoryId getId() {
        return this.id;
    }
    
    public void setId(PatientHistoryId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Disease_id", nullable=false, insertable=false, updatable=false)
    public Diseases getDiseases() {
        return this.diseases;
    }
    
    public void setDiseases(Diseases diseases) {
        this.diseases = diseases;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Patient_id", nullable=false, insertable=false, updatable=false)
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }




}


