package bloodbank.entites;
// Generated May 13, 2022 3:58:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name="staff"
    ,catalog="blood_bank"
)
public class Staff  implements java.io.Serializable {


     private Integer empId;
     private EmpJobs empJobs;
     private String firstName;
     private String lastName;
     private String gender;
     private String address;
     private String bloodType;
     private String natId;
     private Date dateOfBirth;
     private String primaryNumber;
     private String secondaryNumber;
     private String salary;
     private Set<Donors> donorses = new HashSet<Donors>(0);
     private Set<BloodTransactions> bloodTransactionses = new HashSet<BloodTransactions>(0);
     private Set<Patients> patientses = new HashSet<Patients>(0);
     private Set<BloodStock> bloodStocks = new HashSet<BloodStock>(0);

    public Staff() {
    }

	
    public Staff(EmpJobs empJobs, String firstName, String lastName, String gender, String address, String bloodType, String natId, Date dateOfBirth, String primaryNumber, String salary) {
        this.empJobs = empJobs;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.address = address;
        this.bloodType = bloodType;
        this.natId = natId;
        this.dateOfBirth = dateOfBirth;
        this.primaryNumber = primaryNumber;
        this.salary = salary;
    }
    public Staff(EmpJobs empJobs, String firstName, String lastName, String gender, String address, String bloodType, String natId, Date dateOfBirth, String primaryNumber, String secondaryNumber, String salary, Set<Donors> donorses, Set<BloodTransactions> bloodTransactionses, Set<Patients> patientses, Set<BloodStock> bloodStocks) {
       this.empJobs = empJobs;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.address = address;
       this.bloodType = bloodType;
       this.natId = natId;
       this.dateOfBirth = dateOfBirth;
       this.primaryNumber = primaryNumber;
       this.secondaryNumber = secondaryNumber;
       this.salary = salary;
       this.donorses = donorses;
       this.bloodTransactionses = bloodTransactionses;
       this.patientses = patientses;
       this.bloodStocks = bloodStocks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EMP_id", unique=true, nullable=false)
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Job_id", nullable=false)
    public EmpJobs getEmpJobs() {
        return this.empJobs;
    }
    
    public void setEmpJobs(EmpJobs empJobs) {
        this.empJobs = empJobs;
    }

    
    @Column(name="firstName", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="Gender", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="Address", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Blood_Type", nullable=false, length=45)
    public String getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    
    @Column(name="Nat_id", nullable=false, length=45)
    public String getNatId() {
        return this.natId;
    }
    
    public void setNatId(String natId) {
        this.natId = natId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_of_birth", nullable=false, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="Primary_Number", nullable=false, length=45)
    public String getPrimaryNumber() {
        return this.primaryNumber;
    }
    
    public void setPrimaryNumber(String primaryNumber) {
        this.primaryNumber = primaryNumber;
    }

    
    @Column(name="Secondary_Number", length=45)
    public String getSecondaryNumber() {
        return this.secondaryNumber;
    }
    
    public void setSecondaryNumber(String secondaryNumber) {
        this.secondaryNumber = secondaryNumber;
    }

    
    @Column(name="Salary", nullable=false, length=100)
    public String getSalary() {
        return this.salary;
    }
    
    public void setSalary(String salary) {
        this.salary = salary;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="staff")
    public Set<Donors> getDonorses() {
        return this.donorses;
    }
    
    public void setDonorses(Set<Donors> donorses) {
        this.donorses = donorses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="staff")
    public Set<BloodTransactions> getBloodTransactionses() {
        return this.bloodTransactionses;
    }
    
    public void setBloodTransactionses(Set<BloodTransactions> bloodTransactionses) {
        this.bloodTransactionses = bloodTransactionses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="staff")
    public Set<Patients> getPatientses() {
        return this.patientses;
    }
    
    public void setPatientses(Set<Patients> patientses) {
        this.patientses = patientses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="staff")
    public Set<BloodStock> getBloodStocks() {
        return this.bloodStocks;
    }
    
    public void setBloodStocks(Set<BloodStock> bloodStocks) {
        this.bloodStocks = bloodStocks;
    }




}


